### ISSUE TITLE
Keeps saying "Please try again"

### ISSUE THREAD

**Issue by Th3-A6add0n** [Maayur28/PriceTrackerUI#1]
Website used: Flipkart
Platform: Android 
Browser: Chrome
Problem faced: Whenever I try to check the price by pasting the product link it says "Please try again".
SS attached
![Screenshot_20230813-073837-417](https://github.com/Maayur28/PriceTrackerUI/assets/34588916/d54168d1-716d-4357-b545-2d1172c80263)

**Comment by Maayur28** [comment]
Hi,
Thanks for reaching out.
We are migrating to new website with better UI and more features.
So we have stopped the services on this existing website.
Will update the new website link soon.

Thanks
